# 1. Veritabanı Bağlantı Ayarları
spring.datasource.url=jdbc:postgresql://localhost:5433/mydb
spring.datasource.username=elifnurdonmez
spring.datasource.password=77092766
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate (JPA) Ayarları
spring.jpa.hibernate.ddl-auto=update

# Konsolda yapılan SQL sorgularını görmek için
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. Uygulama Portu
# Spring Boot varsayılan olarak 8080'de çalışır:
server.port=8080